import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import "./globals.css";
import ReactQueryProvider from "@/providers/react-query";

const spaceGroktesk = Space_Grotesk({
  variable: "--font-space-groktesk",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGroktesk.variable} antialiased bg-background !font-space-groktesk`}
      >
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
